/*
PuLSE-test version 1.2
Copyright(c) 2017 Steven Shave

Distributed under the MIT license

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files(the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions :

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
#include "../src/PuLSE-HTMLWriter.hpp"
#include "../src/PuLSE-RunData.hpp"
#include <array>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <memory>
#include <set>
#include <string>
#include <tuple>
#include <utility>
#include <vector>

int main(int argc, char **argv) {
  auto compareTables = [](const std::vector<std::vector<std::string>> &a,
                          std::vector<std::vector<std::string>> &b) {
    if (a.size() == 0 || b.size() == 0)
      return false;

    if (a.size() != b.size())
      return false;

    if (a[0].size() != b[0].size())
      return false;

    for (unsigned i = 0; i < a.size(); ++i) {
      for (unsigned j = 0; j < a[i].size(); ++j) {
        if (strcmp(a[i][j].c_str(), b[i][j].c_str()) != 0) {
          return false;
        }
      }
    }
    return true;
  };

  constexpr char testData[] =
      "NTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCACATCTATCTCATGCTGT\nNGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGGAGTGACAGGCTAAGCAAGC\n"
      "NTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTCAAGAATGTCTGTGTGT\nNTTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCAGGGAGGCCTCCCCGTGT\n"
      "NGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAACTTATCAGCGGCCCGCAAGC\nNTTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTGGTTGCCCGAGTGATGT\n"
      "NTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCGTGGTGATCCTTAGTGT\nNGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGTAAAGGTCAACTAGGCAAGC\n"
      "NTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTGTAGTTAGACACATTGT\nNGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAGATTAACGACTAATGCAAGC\n"
      "NTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTCGGAAGTACCTTCATGT\nNGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACTGGCTCCCACATGCAAGCCG\n"
      "NTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCAATCCATAATACACTTGT\nNTTAAAGAGGAGAAATTAACCATGAAAAAGATTTGG"
      "CTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTTTATTTTTATAGATTGTGCTG\n"
      "NGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAATAGGCATACAACGAGCAAGC\nNTTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCATAGTGTGGCTGCGGTGG\n"
      "NGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACTGACATATAAGCGGGCAAGC\nNTTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTATTCCTTAGTGTTATGT\n"
      "NGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACTGCGACCCGACCAAGCAAGC\nNGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGTCCGCGGTAAGTTTGCAAGC\n"
      "NTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCACTGCATTTTCTTTGTGT\nNTTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCCATTTGCGGCTACCTGT\n"
      "NGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAGACAACTGGCAGGGGGCAAGC\nNTTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTCGTTCGCCCGAACTTGT\n"
      "NTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGATGTTTAGATATTATGT\nNGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCAGCCGCCATGGCCGGCTGAGCTGCCAGCAGCAGCAAGCCAGCGGCTGCCGTAGGCAATAG\n"
      "NTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTTTAGTTTTTCATTTTGT\nNGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACAGCAGAGTGTAGATGGCAAG\n"
      "NGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAATTCACGCGATCCCGGCAAGC\nNTTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGTATGTACTATGTGTTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCCACAGCTGACTAAACCCAGGCAAG\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTGCAGGTGGCAGTGGGGGTAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCCTGCAGTAAGTTTCAACAGTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAAGGAAAAGAAGGCAGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGCTAGTACTTCATTTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGCTTACCTGTTTTTTTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTTTACGATCAGCTCTTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGCGTGATGCTTCTCGGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTTTGAGGATTCACCGTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACGAAAAGCATGCTGTGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCGCTAAACGCTAAAACTAAACCAGCCAGCGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAAAGATCAACTTAGAGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCATGGGCAATGCAGGATGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAACAAGAGAAGACTCGGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCATTGAACTGCTGCAATGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGGTGCTGTCACATGGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAATGAATAACCGCTCTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTAGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCGAGATAGCTGACCTTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGGAGATGTATACTATTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAACAAGTAGCGTTGCAAGCCG\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTATCTTGTAGCAGAATGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAAAAGAAAAAGGACAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACAAATACAAATTCTAGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCATTTATATCGCAGATTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCAACAAACTCTCTTCTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTCACTGCTTTTAGGTTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACTAAACAGACGAGCTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTAACTTTACCATTTTTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCATCGCTGCCTTGACTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCTGCGAGCGGTAGTATGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAAGATAAACGAAAGGGGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGGACGTGAATGTAAATGT\n"
      "NTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTAGTTTTAGCGTTTAGC"
      "GCCATGGCGGCTTGCTGTTCGGGCAGTTTGTGTG\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAACGCAGAGCAAATGTGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCCTATTGTTCGACCATGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACGTAAAAAAAGGACGGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGATAGGGTTGTAAGGTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACCCCCCACAGGGGATGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAACTAAAGAAACCACAGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCACTTTCCCTTCTTTCTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTAGAATCTGATTTGTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGGATACGGGGGTCTATGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCAGGTTACGATTAAGTGT\nCGTGACTATTTTCGTGATATTGGTCGTATGGTTCTT"
      "GCTGCCGAGGGTCGCAAGGCTAATGATTCACACGCCGACTGCTATCAGTATTTTTGTGTGCCTGAGTATG\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAATTCGTTGCGCGGACAAGCCG\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACATGAAAATAAAAAATCGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATCGCACAAGGGCGCAGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTGTTATTCGTTTGTGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATGGGCGAACTGTATGGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTCTTATTGATGTGTTTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTGTTTTTTTTCCTTGTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCCTAATAGTCCGGTATGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTGGATAAGTGGGACCTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACGCACAACTAACTCTCCCGAAGCAAGCCGCCA\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCAGAATCGTACAGTGATGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCCACCACAGGCTGGAAAGCAAGCAA\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCAGTAGGTCGAGCGTGTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGCTTGCGTCGACTCATCTTATTGTG\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCAACGCTTCAGACTATTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAATTACCTTTACCGCAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCGGAAAGCCAAACCGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGGTAGGTTCTTGGCTTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCAGGACGATCGCGGTTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGCCCCAAAGAATCAGCAAGCC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCTTAGTCTTTTTAGATGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTCTACAACTCTCTCATGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAAGTATCGGTAGGAAAGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTTTGATTCACTAATCTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAGAGCGAGTACTAACGGCAAGC\nTTCATTAAAGAGGAGAAATTAACCATGAAAAAGATT"
      "TGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGTGTCAAGGTACTTGTGTG\n"
      "TCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCG"
      "CCATGGCGGCTTGCGTTATATGGTAGATTTGTGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTCTCAGAGCGCGTTGTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCATTTCCTGCCTTTCTTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACGCAGATACGAGACTGCAAGC\n"
      "CATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCAC"
      "CTGCAGCACATGGTATGACAAAACGGCAAGCCGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGCCCAAATGTCAAGGGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATGCATGGTACATACGGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACATTGATCAATCATATCGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTTTCCCGGTAGGGTCTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGGCAATAAGGAATTGCAAGCC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGGCTTGCCGCCCGAGACCAGATTG\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGGTGATAATCCACGTGTGCT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATCTGACATCAGTTGGGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCAGTCCGACGACTTTGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAACTACGAAATGTAGGGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACATATTTCACCCATAGCGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACTTGCCTGATGCACCGCAAGC\nATTCATTAAAGATGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCGTGGTGCGGTTGTATGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACATCTAGTCAAACATGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACCGGGAGATGCATGAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACTACGTCCCGAAACCGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAAAGAACGGAAGACGGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGGCGATTGGATGCGGTTG\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGTGCATCTACTTTGTTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGGTATGAATGACTCTTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACATGTAACACTCTGCTAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAGGGGTGTAGATGCCAGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTGCATTTATGACTATTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCCGCCATGGCGCTAAACGCTAAAAC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCCTATAATTTGTTGGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCCTACGCGCCTGTATTGCAAGCCGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGCCATCAATTACTTGTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCAGACTCTCGTGGTTTTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAATCCCGATCGACAACGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTTAGATAGAACTAAGTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGGCGTTTGCTTGTAGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATGAAAAAACCGATGAGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGTGACGCTTATGGTCTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCAGTGTTTTGCCCAGATGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCTGTCGGTCAGATCATGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGAACTAAGGCTCGGTTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAACCTAAGCTAATAAAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAAACCAGCAATTACCGCAAGCC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACTAAACGCCCCCCGAGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTCTAATGCTATCTCATGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCACTCTTTTCTTTTTCTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCGGTGTGTGTGGATTTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAATTCAGACAAACCGCAAGCC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACGGGCCTGTTAATAAGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGAAGGCTATAGTAAGGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACGGAGTAGTAGGACTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTGAATGATACCATTTTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCGCACGTCTTCGGCGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACGTCGCAACGGATCGGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGGTTTGCGAAACCCGTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAACAGGAGGGAGGAACGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCGGGTGGGACTTTCGTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGAGTTACGCTGACTTGCCAAG\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTGACGTCTTGGCATATGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTTTTTCTTTGCTTCTTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACAAGAAATCCACTGAGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGTGGCTTGCTAGAGCCTCTTGATGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCTGAAACAATGACTGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAAACCCCTCCGGCCAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCCGCATCAGCGCGAAGCAAG\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTTTTCCTCGGGCATTTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTGACCTTGGGGGCTTGTG\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTTGCATTTGCATTACTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAAAAATAGGTGGCTTTGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACAAACTATTAGATCTGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGATGCTTCGGCAGCTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCAGAGCGGAACGCATTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTAGACGGCTTCCCTTTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGAAAACCCGCAAGCAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCCTTGTTAATTCCTGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACATGCTTACGGAATCGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATACAACCGCAGCATGGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGATGGTAGGGCCCGTGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGAACGGGACTATTTGTGC\nTAGGAGGAGAAATTAACCATGAAAAAGATTTGGCTG"
      "GCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCACATCTCGTGTTAATGTGCTGCAG\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGTAGACAGTTGTTAATGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGGGCTCGAGGAGGGTGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACGGTGTGAATTCATAGCAACC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACATTACTGCCTGAAACAGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTTGAATCAGTCCCGAGTG\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTGTAGTTCTCTGTATTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCACATTTGAGTCGAAAATCGCAAGCCGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGTCATTAGTTGTTTGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAATATCCTGCCTATTCGCAAGC\nTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTT"
      "GGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCAGTTACAGGTTATGTGTGG\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCCAACAGCAGGTCCACCGATGGCAA\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTCGGATTGTCTATCTTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAGTTCTCTAACGTCTCGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAACAGAGATTAACAAGGCAAG\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAAGAGACCCAAAAATAGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACGAAAGCCCAACGGCCGCAAGCC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACATCCCGCAGGCAAGCAAGCC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACACTAATTGAATTGGGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTGCTTGACCCTAAGTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCTTGAGTTAGATACCTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATAGGTACCTAGTTTGGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTGTAACGCAGCGGCGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAGTAGACAGATCTATGGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGCGGTCTGTGTTTCGTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGTTCTTTTCTCTCTTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCAAGCTTGTGTTTCATTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTATTTGACCTCTGCCTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAATTAGACATCAAGTAGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCGCGAAAGTGGTATTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCGGTTGTCTTTTCAGCTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCCGTTACTAATTGTGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGAAAACCTGTGAACAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAGAAGGGTCTAGTTGGCAAGCC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCATTACATAGGTCTGCTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGTACCTTGAATTCTGTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGGCGTCCGAGTTTCGTGTAT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCACTTTACCCAATGATGTG\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGAACGGGTGGAAATGGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCAGGCCAGCCGCGGATGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACATATCCCGGCACTACCCAAGCC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACAGCACTACATGTTAGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAATCACATCTTAAGAAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATCAAGCCATAACATAGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACTACTCTGCAGAGAGGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCCCGTCATAGTTTTTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGTGGCTTGCACTGACTGACTTATATGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATCGCGTTAAATGTTCGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAGGGCATGCGATCCGCAAGCC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCACATGTCGGAACATTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGTTGGCCCCGGAACTGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATAGCACAAAGCCGGTGCAAGC\nCTGACCGTACCGAGGCTAACCCTAATGAGCTTAATC"
      "AAGATGATGCTCGTTATGGTTTCCGTTGCTGCCATCTCAAAAACATTTGGACTGCTCCGCTTCCTCCTGA\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTTAATTTCTTCTAAGTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAAAGCACCCCCTAGTGCAAGC\n"
      "CTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCA"
      "TGGCGGCTTGCTTACTGCTCTCGTCGTGTGCTGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACATAAAGGGTCAGGGTGAGCCGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAGAAAGAAAGAGTTAAGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGGGCTTGCAATCACTGGTGATTTTGTG\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATGCTAAAGATAGTAGGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGAAATTCAAATTTGTGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATCTACAAGTGATATCGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTGCTTTTCCTCCTGCTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCCACTGTTTGTTAGTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCCGGCTTGCGTCCTGACCGTTTGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAACCAACATCTGCACGGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCATTTATTCTTGTCATTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCCTGTGCCGCAATTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCAGTTGTTCGTCTTCTTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAAAGGGACCCCTATCTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCTGTATATGAATTAGTGT"
      "\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACT"
      "GCCACCTGCAGCACAGAAAACCTGTGAACAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAGAAGGGTCTAGTTGGCAAGCC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCATTACATAGGTCTGCTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCGTACCTTGAATTCTGTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGGCGTCCGAGTTTCGTGTAT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCACTTTACCCAATGATGTG\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGAACGGGTGGAAATGGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCAGGCCAGCCGCGGATGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACATATCCCGGCACTACCCAAGCC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACAGCACTACATGTTAGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAATCACATCTTAAGAAGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATCAAGCCATAACATAGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACACTACTCTGCAGAGAGGCAAGC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCCCGTCATAGTTTTTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGTGGCTTGCACTGACTGACTTATATGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATCGCGTTAAATGTTCGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAGGGCATGCGATCCGCAAGCC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCACATGTCGGAACATTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGTTGGCCCCGGAACTGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATAGCACAAAGCCGGTGCAAGC\nCTGACCGTACCGAGGCTAACCCTAATGAGCTTAATC"
      "AAGATGATGCTCGTTATGGTTTCCGTTGCTGCCATCTCAAAAACATTTGGACTGCTCCGCTTCCTCCTGA\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTTAATTTCTTCTAAGTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAAAGCACCCCCTAGTGCAAGC\n"
      "CTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCA"
      "TGGCGGCTTGCTTACTGCTCTCGTCGTGTGCTGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACATAAAGGGTCAGGGTGAGCCGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAGAAAGAAAGAGTTAAGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGGGCTTGCAATCACTGGTGATTTTGTG\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATGCTAAAGATAGTAGGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGAAATTCAAATTTGTGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATCTACAAGTGATATCGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTGCTTTTCCTCCTGCTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCCACTGTTTGTTAGTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCCGGCTTGCGTCCTGACCGTTTGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAACCAACATCTGCACGGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCATTTATTCTTGTCATTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCCTGTGCCGCAATTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCAGTTGTTCGTCTTCTTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAAAGGGACCCCTATCTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCTGTATATGAATTAGTGT"
      "\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACT"
      "GCCACCTGCAGCACAAGGGCATGCGATCCGCAAGCC\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCACATGTCGGAACATTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGTTGGCCCCGGAACTGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATAGCACAAAGCCGGTGCAAGC\nCTGACCGTACCGAGGCTAACCCTAATGAGCTTAATC"
      "AAGATGATGCTCGTTATGGTTTCCGTTGCTGCCATCTCAAAAACATTTGGACTGCTCCGCTTCCTCCTGA\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCTTAATTTCTTCTAAGTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAAAAGCACCCCCTAGTGCAAGC\n"
      "CTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCA"
      "TGGCGGCTTGCTTACTGCTCTCGTCGTGTGCTGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACATAAAGGGTCAGGGTGAGCCGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAGAAAGAAAGAGTTAAGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGGGCTTGCAATCACTGGTGATTTTGTG\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATGCTAAAGATAGTAGGCAAGC\nCGTCATCGTCTAACTTTAAATAATTGGCATTATTTA"
      "AAGTTACTGCATTACTGCCTCCGCTACCCCCACTGCCACCTGCAGCACAGAAATTCAAATTTGTGCAAGC\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACATCTACAAGTGATATCGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCTGCTTTTCCTCCTGCTGT\n"
      "ATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAG"
      "CGCCATGGCGGCTTGCCCACTGTTTGTTAGTTGT\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCCGGCTTGCGTCCTGACCGTTTGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAACCAACATCTGCACGGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCATTTATTCTTGTCATTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCCTGTGCCGCAATTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCAGTTGTTCGTCTTCTTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAAAGGGACCCCTATCTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCTGTATATGAATTAGTGT"
      "\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTT"
      "AGCGCCATGGCCGGCTTGCGTCCTGACCGTTTGTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAACCAACATCTGCACGGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCATTTATTCTTGTCATTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCCTGTGCCGCAATTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCAGTTGTTCGTCTTCTTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAAAGGGACCCCTATCTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCTGTATATGAATTAGTGT"
      "\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGATTTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTT"
      "AGCGCCATGGCCGGCTTGCGTCCTGACCGTTTGTGT\nCGTCATCGTCTAACTTTAAATAATTGGCATTATT"
      "TAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAACCAACATCTGCACGGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCATTTATTCTTGTCATTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACACCCTGTGCCGCAATTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCAGTTGTTCGTCTTCTTGT\n"
      "CGTCATCGTCTAACTTTAAATAATTGGCATTATTTAAAGTTACTGCATTACTGCCTCCGCTACCCCCACTGC"
      "CACCTGCAGCACAAAGGGACCCCTATCTGCAAGC\nATTCATTAAAGAGGAGAAATTAACCATGAAAAAGAT"
      "TTGGCTGGCGCTGGCTGGTTTAGTTTTAGCGTTTAGCGCCATGGCGGCTTGCCTGTATATGAATTAGTGT"
      "\n";

  std::cerr << "Running PuLSE tests...\nGenerating testInput.fastq & "
               "testInput.html (Will be "
               "deleted after tests have completed).\n";
  std::ofstream outTestFile("testInput.fastq");
  if (outTestFile) {
    outTestFile << testData;
    outTestFile.close();
  } else {
    std::cerr << "Could not write testInput.fastq in the current working "
                 "directory, please move to a writable location and rerun "
                 "pulse-test\n";
    return (1);
  }

  auto rundata = std::make_shared<RunData>("testInput.fastq",
                                           "CGTTGCXXXXXXXXXXXXXXXTGTGCT");
  {
    PuLSEHTMLWriter htmlwriter(rundata);
    rundata->ReadSequences();
    htmlwriter.WriteRunInfo();
    rundata->PopulateBasicStats();
    htmlwriter.WriteBasicStats();
    rundata->PopulateCumulativeOccurances();
    htmlwriter.WriteCumulativeCounts();
    rundata->PopulateCommonOccurances();
    htmlwriter.WriteCommonOccurances();
    rundata->PopulateHeatmaps();
    htmlwriter.WriteHeatMaps();

    {
      std::vector<std::vector<std::string>> nProtRes(
          21, std::vector<std::string>());
      auto elementNProtRes = nProtRes.begin();
      *elementNProtRes = {"F", "4", "10", "9", "10", "20"};
      ++elementNProtRes;
      *elementNProtRes = {"L", "10", "13", "16", "8", "16"};
      ++elementNProtRes;
      *elementNProtRes = {"I", "1", "6", "3", "3", "2"};
      ++elementNProtRes;
      *elementNProtRes = {"M", "1", "3", "3", "0", "2"};
      ++elementNProtRes;
      *elementNProtRes = {"V", "2", "5", "9", "22", "2"};
      ++elementNProtRes;
      *elementNProtRes = {"S", "12", "12", "9", "18", "7"};
      ++elementNProtRes;
      *elementNProtRes = {"P", "5", "7", "3", "2", "7"};
      ++elementNProtRes;
      *elementNProtRes = {"T", "14", "9", "7", "11", "4"};
      ++elementNProtRes;
      *elementNProtRes = {"A", "2", "11", "7", "7", "5"};
      ++elementNProtRes;
      *elementNProtRes = {"Y", "5", "0", "2", "3", "2"};
      ++elementNProtRes;
      *elementNProtRes = {"H", "5", "6", "3", "2", "1"};
      ++elementNProtRes;
      *elementNProtRes = {"Q", "1", "1", "3", "2", "1"};
      ++elementNProtRes;
      *elementNProtRes = {"E", "4", "3", "1", "5", "0"};
      ++elementNProtRes;
      *elementNProtRes = {"N", "5", "5", "1", "4", "6"};
      ++elementNProtRes;
      *elementNProtRes = {"K", "1", "1", "1", "0", "1"};
      ++elementNProtRes;
      *elementNProtRes = {"D", "6", "0", "10", "2", "3"};
      ++elementNProtRes;
      *elementNProtRes = {"C", "9", "6", "3", "8", "2"};
      ++elementNProtRes;
      *elementNProtRes = {"W", "2", "0", "1", "0", "0"};
      ++elementNProtRes;
      *elementNProtRes = {"R", "21", "4", "6", "3", "13"};
      ++elementNProtRes;
      *elementNProtRes = {"G", "3", "7", "19", "6", "15"};
      ++elementNProtRes;
      *elementNProtRes = {"*", "4", "8", "1", "1", "8"};

      if (!compareTables(nProtRes, rundata->protheatmap)) {
        std::cerr << "Tests failed\n";
        return 1;
      }
    }

    {
      std::vector<std::vector<std::string>> nDNABases(
          4, std::vector<std::string>());
      auto elementNDNABases = nDNABases.begin();
      *elementNDNABases = {"A",  "37", "31", "35", "28", "23", "22", "22",
                           "22", "21", "20", "19", "17", "22", "20", "26"};
      ++elementNDNABases;
      *elementNDNABases = {"T",  "33", "18", "56", "42", "37", "41", "31",
                           "40", "44", "45", "43", "44", "40", "42", "35"};
      ++elementNDNABases;
      *elementNDNABases = {"C",  "30", "26", "17", "21", "39", "29", "18",
                           "23", "23", "10", "36", "31", "30", "21", "23"};
      ++elementNDNABases;
      *elementNDNABases = {"G",  "17", "42", "9",  "26", "18", "25", "46",
                           "32", "29", "42", "19", "25", "25", "34", "33"};
      if (!compareTables(nDNABases, rundata->dnaheatmap)) {
        std::cerr << "Tests failed\n";
        return 1;
      }
    }
  }
  std::cerr << "Tests passed!\n";

  if (remove("testInput.fastq") != 0)
    std::cerr << "Error deleting testInput.fastq, please remove it manually\n";
  if (remove("testInput.html") != 0)
    std::cerr << "Error deleting testInput.html, please remove it manually\n";

  return 0;
}
